### ISSUE TITLE
Index views only need links to listing, not full content

### ISSUE THREAD

**Issue by claudinec** [claudinec/singingfromthelectionary#42]

**Comment by claudinec** [comment]
This only applies to Lectionary Index and Other Occasions.

**Comment by LectionarySinger** [comment]
It should list only those scripture references that appear as a "group" in an entry (e.g. it links to all the songs suggested for Jeremiah 2:4-13. At the moment, it lists every reference, but does not actually link to anything.

Also, I can't work out how to edit the list; they need to be listed in "Order of Appearance" since that's how most people would search for them.

**Comment by claudinec** [comment]
Which index are your referring to here?
